# All venues in the United States
PREFIX mv:   <http://getexcited.com/music-venues#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?venueName ?cityLabel
WHERE {
  ?venue mv:name ?venueName ;
         mv:isLocatedIn ?city .
  ?city rdfs:label ?cityLabel ;
        mv:locatedInCountry mv:UnitedStates .
}
ORDER BY ?cityLabel
