PREFIX mv:   <http://getexcited.com/music-venues#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?venue ?name ?typeName ?cityName ?capacity
WHERE {
    ?type   rdfs:subClassOf  mv:IndoorVenue .
    ?venue  a                ?type ;
            mv:name          ?name ;
            mv:isLocatedIn   ?city ;
            mv:hasSeatingCapacity ?capacity .

    ?city   mv:locatedInCountry  mv:UnitedStates ;
            rdfs:label           ?cityName .

    ?type   rdfs:label           ?typeName .
}
ORDER BY ?cityName ?name
